# Use root/example as user/password credentials
version: '3.1'

services:

  mongo-1:
    image: mongo:latest
    restart: always
    hostname: mongo-1
    container_name: mongo-1
    networks:
      - mongocluster
    ports:
      - 30001:27017
    command: mongod --replSet comments
 
    
  mongo-2:
    image: mongo:latest
    restart: always
    hostname: mongo-2
    container_name: mongo-2
    networks:
      - mongocluster
    ports:
      - 30002:27017
    command: mongod --replSet comments

  mongo-3:
    image: mongo:latest
    restart: always
    hostname: mongo-3
    container_name: mongo-3
    networks:
      - mongocluster
    ports:
      - 30003:27017
    command: mongod --replSet comments
 

networks:
  mongocluster:
    driver: bridge